blueprint:
  name: ESPSomfy Vertical Blinds State Tracker
  description: Tracks the state of vertical blinds for automations
  domain: automation
  input:
    blind_id:
      name: Blind ID
      description: Unique identifier for this blind (dining, lounge, etc)
      selector:
        text:
    state_tracker:
      name: State Tracker Entity
      description: Input select helper with options - open, closed, my, unknown
      selector:
        entity:
          domain: input_select

trigger:
  - platform: event
    event_type: vertical_blinds_control

action:
  - variables:
      blind_id_input: !input blind_id
      event_blind_id: "{{ trigger.event.data.blind_id | default('none') }}"
      event_command: "{{ trigger.event.data.command | default('none') }}"
  
  - condition: template
    value_template: "{{ event_blind_id == blind_id_input }}"
  
  - choose:
      - conditions:
          - "{{ event_command == 'open' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input state_tracker
            data:
              option: open
      - conditions:
          - "{{ event_command == 'close' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input state_tracker
            data:
              option: closed
      - conditions:
          - "{{ event_command == 'my' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input state_tracker
            data:
              option: my
      - conditions:
          - "{{ event_command == 'stop' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input state_tracker
            data:
              option: unknown

mode: single