# ESPSomfy Vertical Blinds Configuration
# Only ONE script per blind is required!

input_select:
  # Dining room position tracker (33% middle)
  dining_blinds_position:
    name: Dining Blinds Position
    options:
      - "0"
      - "33"
      - "100"
    initial: "100"
  
  # Lounge position tracker (50% middle)
  lounge_blinds_position:
    name: Lounge Blinds Position
    options:
      - "0"
      - "50"
      - "100"
    initial: "100"

# Example Dashboard Configuration
dashboard_example:
  type: vertical-stack
  cards:
    - type: markdown
      content: "## Vertical Blinds Control"
    
    # Dining Room Controls
    - type: markdown
      content: "### Dining Room"
    
    - type: horizontal-stack
      cards:
        - type: button
          name: Open
          icon: mdi:blinds-open
          tap_action:
            action: call-service
            service: script.dining_blinds_controller
            data:
              position: 100
        
        - type: button
          name: 33%
          icon: mdi:blinds
          tap_action:
            action: call-service
            service: script.dining_blinds_controller
            data:
              position: 33
        
        - type: button
          name: Close
          icon: mdi:blinds-closed
          tap_action:
            action: call-service
            service: script.dining_blinds_controller
            data:
              position: 0
    
    # Lounge Controls
    - type: markdown
      content: "### Lounge"
    
    - type: horizontal-stack
      cards:
        - type: button
          name: Open
          icon: mdi:blinds-open
          tap_action:
            action: call-service
            service: script.lounge_blinds_controller
            data:
              position: 100
        
        - type: button
          name: 50%
          icon: mdi:blinds
          tap_action:
            action: call-service
            service: script.lounge_blinds_controller
            data:
              position: 50
        
        - type: button
          name: Close
          icon: mdi:blinds-closed
          tap_action:
            action: call-service
            service: script.lounge_blinds_controller
            data:
              position: 0
    
    # Current Position Display
    - type: entities
      title: Current Positions
      entities:
        - entity: input_select.dining_blinds_position
          name: Dining Room
        - entity: input_select.lounge_blinds_position
          name: Lounge

# Script Creation Guide:
#
# For each blind, create ONE script using the blueprint:
#
# 1. Go to Settings → Automations & Scenes → Scripts
# 2. Create Script → Use Blueprint
# 3. Select "ESPSomfy Vertical Blinds Controller"
# 4. Configure:
#    - Blind Entity: cover.dining_blinds
#    - Position Tracker: input_select.dining_blinds_position
#    - Position Values: Closed=0, Middle=33, Open=100
#    - Timings: Your measured times in milliseconds
# 5. Save with a descriptive name like "dining_blinds_controller"
#
# The script accepts a position parameter when called:
#   service: script.dining_blinds_controller
#   data:
#     position: 33
#
# You can test from Developer Tools → Services:
# Service: script.dining_blinds_controller
# Data (YAML):
#   position: 50