# Minimal configuration needed for the self-contained blueprint
# Only ONE helper per blind is required!

input_select:
  # Dining room position tracker (33% middle)
  dining_blinds_position:
    name: Dining Blinds Position
    options:
      - "0"
      - "33"
      - "100"
    initial: "100"
  
  # Lounge position tracker (50% middle)
  lounge_blinds_position:
    name: Lounge Blinds Position
    options:
      - "0"
      - "50"
      - "100"
    initial: "100"

# That's it! All timings are configured within each script.
# No input_number helpers needed anymore.

# Example Dashboard Configuration:
dashboard_example:
  type: vertical-stack
  cards:
    - type: markdown
      content: "## Vertical Blinds Control"
    
    # Dining Room Controls
    - type: markdown
      content: "### Dining Room"
    
    - type: horizontal-stack
      cards:
        - type: button
          name: Open
          icon: mdi:blinds-open
          tap_action:
            action: call-service
            service: script.dining_blinds_open
        
        - type: button
          name: 33%
          icon: mdi:blinds
          tap_action:
            action: call-service
            service: script.dining_blinds_33
        
        - type: button
          name: Close
          icon: mdi:blinds-closed
          tap_action:
            action: call-service
            service: script.dining_blinds_close
    
    # Lounge Controls
    - type: markdown
      content: "### Lounge"
    
    - type: horizontal-stack
      cards:
        - type: button
          name: Open
          icon: mdi:blinds-open
          tap_action:
            action: call-service
            service: script.lounge_blinds_open
        
        - type: button
          name: 50%
          icon: mdi:blinds
          tap_action:
            action: call-service
            service: script.lounge_blinds_50
        
        - type: button
          name: Close
          icon: mdi:blinds-closed
          tap_action:
            action: call-service
            service: script.lounge_blinds_close
    
    # Current Position Display
    - type: entities
      title: Current Positions
      entities:
        - entity: input_select.dining_blinds_position
          name: Dining Room
        - entity: input_select.lounge_blinds_position
          name: Lounge

# Script Creation Guide:
#
# For each blind, create 3 scripts using the blueprint:
#
# 1. OPEN Script:
#    - Target Position: 100
#    - All timings configured in the script
#
# 2. MIDDLE Script:
#    - Target Position: 33 (or 50 for lounge)
#    - Same timings as open script
#
# 3. CLOSE Script:
#    - Target Position: 0
#    - Same timings as open script
#
# The timings only need to be configured once per blind,
# then copied to all three scripts for that blind.